using System.Collections.Concurrent;
using System.IO;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Hosting;
using SIPSorcery.Net;

namespace WebVirtualDisplayClient;

class WebServer : BackgroundService
{
        private static string? _latestOffer;
        private static string? _latestAnswer;
        private static readonly List<string> _iceCandidates = new();

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
                var builder = WebApplication.CreateBuilder();

                builder.Services.AddCors(options => {
                                options.AddPolicy("AllowReact", p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod());
                                });

                var app = builder.Build();
                app.UseCors("AllowReact");

                app.UseDefaultFiles(); // Serve the index.html file by default

                // serve files from ./wwwroot/
                String currentDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
                app.UseStaticFiles(new StaticFileOptions
                                {
                                FileProvider = new PhysicalFileProvider(currentDir),
                                RequestPath = ""
                                });

                // INFO: to be honest I don't really know webrtc boilerplate
                // I did not write any of the below code.

                // TODO: refactor to a new file
                string? latestOfferSdp = null;
                ConcurrentQueue<String> remoteIceCandidates = new ConcurrentQueue<string>();
                ConcurrentBag<String> localIceCandidates = new ConcurrentBag<string>();
                RTCPeerConnection peerConnection = new RTCPeerConnection(new RTCConfiguration { iceServers = new List<RTCIceServer>() });

                var dataChannel = await peerConnection.createDataChannel("data-stream");

                dataChannel.onopen += () => {
                        Console.WriteLine("🚀 Browser connected! Starting data stream...");

                        // Start a background loop to stream data to the browser
                        // TODO: stream actual data
                        _ = Task.Run(async () => {
                                        int counter = 0;
                                        while (dataChannel.readyState == RTCDataChannelState.open && !stoppingToken.IsCancellationRequested)
                                        {
                                        dataChannel.send($"Hello from C# background worker! Count: {counter++}");
                                        await Task.Delay(1000); // Send data every second
                                        }
                                        });
                };

                dataChannel.onclose += () => Console.WriteLine("Browser disconnected.");

                // 3. Collect local ICE candidates generated by C# to give to the browser
                peerConnection.onicecandidate += (candidate) => {
                        if (!string.IsNullOrEmpty(candidate.candidate)) {
                                localIceCandidates.Add(candidate.candidate);
                        }
                };

                // 4. Generate the local Offer SDP
                var offer = peerConnection.createOffer();

                // tell the server that the browser should be passive I guess????
                offer.sdp = offer.sdp.Replace("a=setup:active", "a=setup:actpass"); 

                await peerConnection.setLocalDescription(offer);
                latestOfferSdp = offer.sdp; // Save it so React can fetch it

                // --- Endpoints Using Native SIPSorcery Types ---
                string generatedOfferSdp = offer.sdp.ToString();

                // React polls this to pull your generated offer text
                app.MapGet("/api/webrtc/offer", () => Results.Text(generatedOfferSdp));

                // React POSTs its browser answer directly into SIPSorcery's initialization model
                app.MapPost("/api/webrtc/answer", async (RTCSessionDescriptionInit answerPayload) => {
                        answerPayload.type = RTCSdpType.answer;
                        peerConnection.setRemoteDescription(answerPayload);
                        return Results.Ok();
                });

                // React polls this to fetch C#'s local ICE candidates
                app.MapGet("/api/webrtc/ice", () => Results.Json(localIceCandidates));

                // React POSTs browser candidates directly into SIPSorcery's ICE init model
                app.MapPost("/api/webrtc/ice", (RTCIceCandidateInit icePayload) => {
                                if (icePayload != null && !string.IsNullOrEmpty(icePayload.candidate)) {
                                peerConnection.addIceCandidate(icePayload);
                                }
                                return Results.Ok();
                                });

                // TODO: Host on 0.0.0.0 so devices across your LAN can connect to port 5000
                await app.RunAsync(stoppingToken);
                // await app.RunAsync("http://0.0.0"); <-- this didn't work
        }
}
