using System.Collections.Concurrent;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Json;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using SIPSorcery.Net;

namespace WebVirtualDisplayClient;

class WebServer : BackgroundService
{
        private static string? _latestOffer;
        private static string? _latestAnswer;
        private static readonly List<string> _iceCandidates = new();

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
                var builder = WebApplication.CreateBuilder();

                builder.Services.AddCors(options => {
                        options.AddPolicy("AllowReact", p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod());
                });

                builder.Services.ConfigureHttpJsonOptions(options => {
                        options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
                });

                var app = builder.Build();
                app.UseCors("AllowReact");

                app.UseDefaultFiles(); // Serve the index.html file by default

                // serve files from ./wwwroot/
                String currentDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
                app.UseStaticFiles(new StaticFileOptions
                {
                        FileProvider = new PhysicalFileProvider(currentDir),
                        RequestPath = ""
                });

                // INFO: to be honest I don't really know webrtc boilerplate
                // I did not write any of the below code.

                // TODO: refactor to a new file
                string? latestOfferSdp = null;
                ConcurrentQueue<String> remoteIceCandidates = new ConcurrentQueue<string>();
                ConcurrentBag<String> localIceCandidates = new ConcurrentBag<string>();
                RTCPeerConnection peerConnection = new RTCPeerConnection(new RTCConfiguration { iceServers = new List<RTCIceServer>() });

                var dataChannel = await peerConnection.createDataChannel("data-stream");

                dataChannel.onopen += () => {
                        Console.WriteLine("🚀 Browser connected! Starting data stream...");

                        // Start a background loop to stream data to the browser

                        // TODO: move this and stream actual real data
                        _ = Task.Run(async () => {
                                int counter = 0;

                                while (dataChannel.readyState == RTCDataChannelState.open && !stoppingToken.IsCancellationRequested) {
                                        dataChannel.send($"Hello from C# background worker! Count: {counter++}");
                                        await Task.Delay(1000); // Send data every second
                                }
                        });
                };

                dataChannel.onclose += () => Console.WriteLine("Browser disconnected.");

                // 3. Collect local ICE candidates generated by C# to give to the browser
                peerConnection.onicecandidate += (candidate) => {
                        if (!string.IsNullOrEmpty(candidate.candidate)) {
                                localIceCandidates.Add(candidate.candidate);
                        }
                };

                // 4. Generate the local Offer SDP
                var offer = peerConnection.createOffer();

                // TODO: include video in the offer (we need to stream video at some point)

                await peerConnection.setLocalDescription(offer);
                latestOfferSdp = offer.sdp; // Save it so React can fetch it

                // --- Endpoints Using Native SIPSorcery Types ---
                string generatedOfferSdp = offer.sdp.ToString();

                app.MapGet("/api/webrtc/offer", () => Results.Text(generatedOfferSdp));

                app.MapPost("/api/webrtc/answer", async (HttpContext ctx, IOptions<JsonOptions> jsonOptions) => {
                        string body = await new StreamReader(ctx.Request.Body).ReadToEndAsync();

                        RTCSessionDescriptionInit? answerPayload;
                        try {
                                answerPayload = JsonSerializer.Deserialize<RTCSessionDescriptionInit>(body, jsonOptions.Value.SerializerOptions);
                        } catch (Exception ex) {
                                Console.WriteLine($"ANSWER DESERIALIZE FAILED: {ex}");
                                return Results.BadRequest(ex.Message);
                        }

                        if (answerPayload == null) {
                                return Results.BadRequest("null payload");
                        }

                        answerPayload.type = RTCSdpType.answer;
                        peerConnection.setRemoteDescription(answerPayload);
                        return Results.Ok();
                });
                app.MapGet("/api/webrtc/ice", () => Results.Json(localIceCandidates));
                app.MapPost("/api/webrtc/ice", async (HttpContext ctx) => {
                        string body = await new StreamReader(ctx.Request.Body).ReadToEndAsync();

                        RTCIceCandidateInit? icePayload;

                        try {
                                icePayload = System.Text.Json.JsonSerializer.Deserialize<RTCIceCandidateInit>(body);
                        } catch (Exception ex) { // failed to deserialize the payload
                                Console.WriteLine($"ICE DESERIALIZE FAILED: {ex}");
                                return Results.BadRequest(ex.Message);
                        }

                        // passes ICE 
                        if (icePayload != null && !string.IsNullOrEmpty(icePayload.candidate)) {
                                peerConnection.addIceCandidate(icePayload);
                                return Results.Ok();

                        } else {
                                return Results.BadRequest();
                        }
                });

                await app.RunAsync("http://0.0.0.0:5000");
        }
}
