<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>wpfui-icon.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="wpfui-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SIPSorcery" Version="10.0.16" />
    <PackageReference Include="WPF-UI" Version="4.2.0" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0 " />
  </ItemGroup>

  <!-- prevent publishing files in wwwroot -->
  <ItemGroup>
          <Content Update="wwwroot\local\**\*.*" CopyToPublishDirectory="Never" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\wpfui-icon-256.png" />
    <None Remove="Assets\wpfui-icon-1024.png" />
  </ItemGroup>

  <ItemGroup>
          <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\wpfui-icon-256.png" />
    <Resource Include="Assets\wpfui-icon-1024.png" />
  </ItemGroup>

</Project>
